---
- hosts: remotes
  remote_user: "{{ansible_ssh_user}}"
  become: true
  gather_facts: no
  tasks:

    - name: Ensure ansible tmp directory exists with correct permissions
      ansible.builtin.file:
        path: "{{pg_home_dir}}/.ansible/tmp"
        state: directory
        mode: '0775'
        owner: postgres
        group: postgres
