---
- hosts: remotes
  remote_user: "{{ansible_ssh_user}}"
  become: true
  become_user: postgres
  vars:
    pg_backup_filename: "{{pg_backup_output_dir}}/pg-backup-{{ansible_hostname}}-{{ansible_date_time.date}}-{{ansible_date_time.hour}}{{ansible_date_time.minute}}.gz"
  tasks:

    - name: Ensure backup directory exists
      file:
        path: "{{pg_backup_output_dir}}"
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'
      become: true
      become_user: root

    - name: Backup pg
      shell: "pg_dumpall | gzip > {{pg_backup_filename}}"

    - name: Calculate sha
      shell: "sha512sum {{pg_backup_filename}} > {{pg_backup_filename}}.sha512"

    - import_tasks: tasks/dropbox_script_tasks.yml

    - name: Upload backup to Dropbox
      ansible.builtin.shell: "python3 ~/dropbox_script.py upload {{pg_backup_filename}} {{pg_backup_filename}}.sha512"
      register: upload_output
      environment:
        DROPBOX_APP_KEY: "{{dropbox_pg_backuper_app_key}}"
        DROPBOX_APP_SECRET: "{{dropbox_pg_backuper_app_secret}}"
        DROPBOX_REFRESH_TOKEN: "{{dropbox_pg_backuper_refresh_token}}"

    - name: Print upload output
      ansible.builtin.debug:
        var: upload_output.stdout

    - name: Delete old backups
      ansible.builtin.shell: "python3 ~/dropbox_script.py list | grep \"pg-backup.*$\" | sort | head -n -20 | xargs -r python3 ~/dropbox_script.py delete"
      register: delete_output
      environment:
        DROPBOX_APP_KEY: "{{dropbox_pg_backuper_app_key}}"
        DROPBOX_APP_SECRET: "{{dropbox_pg_backuper_app_secret}}"
        DROPBOX_REFRESH_TOKEN: "{{dropbox_pg_backuper_refresh_token}}"

    - name: Print delete output
      ansible.builtin.debug:
        var: delete_output.stdout
