---
- hosts: remotes
  remote_user: "{{ansible_ssh_user}}"
  become: true
  become_user: postgres
  tasks:
    - name: Allow user "postgres" connect from local
      community.postgresql.postgresql_pg_hba:
        dest: "{{pg_hba_path}}"
        overwrite: true
        contype: local
        users: postgres
        method: peer
        databases: all

    - name: Allow remote connections
      community.postgresql.postgresql_set:
        name: listen_addresses
        value: "*"
        port: "{{pg_port}}"

    - name: Restart Postgresql
      service:
        name: postgresql
        state: restarted
      become: true
      become_user: root
