---
- hosts: remotes
  remote_user: "{{ansible_ssh_user}}"
  become: true
  gather_facts: no
  tasks:

    - name: Create ansible tmp directory with correct permissions
      ansible.builtin.file:
        path: "{{pg_home_dir}}/.ansible/tmp"
        state: directory
        mode: '0775'
        owner: postgres
        group: postgres

    - name: Ensure backup directory exists
      file:
        path: "{{pg_backup_output_dir}}"
        state: directory
        mode: '0700'
        owner: postgres
        group: postgres

    - name: Copy Python script to remote server
      ansible.builtin.copy:
        src: "{{inventory_dir}}/files/dropbox_script.py"
        dest: "{{pg_home_dir}}/dropbox_script.py"
        mode: '0440'
        owner: postgres
        group: postgres
