---
- hosts: remotes
  remote_user: "{{ansible_ssh_user}}"
  become: true
  gather_facts: no
  tasks:

    - name: Install `pip`
      ansible.builtin.apt:
        name: python3-pip
        update_cache: yes
      become: yes
      become_user: root

#    - name: Install `dropbox` python package
#      ansible.builtin.pip:
#        name: dropbox
#      become: yes
#      become_user: root

    - name: Install `Docker`
      ansible.builtin.apt:
        name:
          - python3-dropbox
        update_cache: yes

    - name: Install `requests` python package
      ansible.builtin.pip:
        name: requests
      become: yes
      become_user: root
