name: "Install Ansible"
runs:
  using: "composite"
  steps:
    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible
      shell: true

    - name: Provide vault password for mikr.us.k122
      env:
        VAULT_PASSWORD: ${{ secrets.VAULT_PASS_MIKR_US_K122 }}
      run: echo "$VAULT_PASSWORD" > ./.mikr.us.k122.vault_pass
      shell: true

    - name: Provide vault password for all
      env:
        VAULT_PASSWORD: ${{ secrets.VAULT_PASS_ALL }}
      run: echo "$VAULT_PASSWORD" > ./.all.vault_pass
      shell: true
