- import_playbook: "{{playbook_dir}}/postgres/init-python.yml"
- import_playbook: "{{playbook_dir}}/postgres/init-postgres.yml"
- import_playbook: "{{playbook_dir}}/postgres/backup.yml"
- import_playbook: "{{playbook_dir}}/postgres/uninstall.yml"
- import_playbook: "{{playbook_dir}}/postgres/install.yml"
- import_playbook: "{{playbook_dir}}/postgres/init-postgres.yml"
- import_playbook: "{{playbook_dir}}/postgres/configure-ssl.yml"
- import_playbook: "{{playbook_dir}}/postgres/configure-connectivity.yml"
- import_playbook: "{{playbook_dir}}/postgres-dbs/prv-test.yml"
- import_playbook: "{{playbook_dir}}/postgres/restore.yml"


