---
- hosts: remotes
  remote_user: "{{ansible_ssh_user}}"
  gather_facts: no
  tasks:

    - name: Uninstall old docker related packages
      apt:
        name:
          - docker.io
          - docker-compose
          - docker-compose-v2
          - docker-doc
          - podman-docker
          - containerd
          - runc
        state: absent

    - name: Install curl/ca-certificates
      apt:
        name:
          - curl
          - ca-certificates
        state: present

    - name: Import the repository signing key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Work out the distribution
      command: lsb_release -sc
      register: distribution

    - name: Work out the architecture
      command: dpkg --print-architecture
      register: architecture

    - name: Add docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{architecture.stdout}}] https://download.docker.com/linux/ubuntu {{distribution.stdout}} stable"
        state: present
        filename: docker

    - name: Install `Docker`
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: yes

    - name: Create a 'docker' group
      ansible.builtin.group:
        name: docker
        state: present
