---
- hosts: remotes
  remote_user: "{{ansible_ssh_user}}"
  gather_facts: no
  tasks:
    - name: Set `MaxSessions` limit
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?MaxSessions'
        line: 'MaxSessions 50'
        state: present
      notify: restart sshd

    - name: Set `MaxStartups`
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?MaxStartups'
        line: 'MaxStartups 50:30:80'
        state: present
      notify: restart sshd

    - name: Set `MaxAuthTries`
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?MaxAuthTries'
        line: 'MaxAuthTries 10'
        state: present
      notify: restart sshd

  handlers:
    - name: restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted
