name: Provide access to VPS

on: workflow_dispatch

jobs:
  access:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Prepare Ansible
        uses: ./.github/actions/prepare-ansible
        with:
          vault_pass_mikr_us_k122: ${{ secrets.VAULT_PASS_MIKR_US_K122 }}
          vault_pass_all: ${{ secrets.VAULT_PASS_ALL }}

      - name: Run Ansible playbook
        run: |
          ansible-playbook ./01-access.yml \
            -l prd \
            --vault-id mikr.us.k122@.mikr.us.k122.vault_pass \
            --vault-id all@.all.vault_pass \
            --inventory ./inventory.yml

      - name: Remove vault passwords
        run: |
          rm ./.mikr.us.k122.vault_pass
          rm ./.all.vault_pass
