name: Provide access to VPS

on: workflow_dispatch

jobs:
  access:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Provide vault password
        env:
          VAULT_PASSWORD: ${{ secrets.VAULT_PASS_MIKR_US_K122 }}
        run: echo "$VAULT_PASSWORD" > ./.mikr.us.k122.vault_pass

      - name: Run Ansible playbook
        run: |
          ansible-playbook ./01-access.yml \
            -l prd \
            --vault-id mikr.us.k122@.mikr.us.k122.vault_pass \
            --inventory ./inventory.yml
          rm ./.mikr.us.k122.vault_pass
