name: Install postgresql in VPS

on: workflow_dispatch

jobs:
  pg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Provide vault password for mikr.us.k122
        env:
          VAULT_PASSWORD: ${{ secrets.VAULT_PASS_MIKR_US_K122 }}
        run: echo "$VAULT_PASSWORD" > ./.mikr.us.k122.vault_pass

      - name: Provide vault password for all
        env:
          VAULT_PASSWORD: ${{ secrets.VAULT_PASS_ALL }}
        run: echo "$VAULT_PASSWORD" > ./.all.vault_pass

      - name: Run Ansible playbook
        run: |
          ansible-playbook ./02-pg.yml \
            -l prd \
            --vault-id mikr.us.k122@.mikr.us.k122.vault_pass \
            --vault-id all@.all.vault_pass \
            --inventory ./inventory.yml

      - name: Remove vault passwords
        run: |
          rm ./.mikr.us.k122.vault_pass
          rm ./.all.vault_pass
